# Site settings

title: Projektowanie stron internetowych | Edyta Subik
description: Responsywne strony internetowe, wizytówki www, blog lub strona oparta na Wordpress (CMS), cięcie szablonów PSD do HTML, opieka nad stroną lub blogiem
email: edytasubik88@gmail.com

# Build settings

markdown: kramdown
permalink: pretty

sass:
  sass_dir: assets/css
  style: :nested

gems:
  - jekyll-sitemap
