# Site settings

title: Projektowanie stron internetowych | Edyta Tarnowska
description: Responsywne strony internetowe, wizytówki www, blog lub strona oparta na Wordpress (CMS), cięcie szablonów PSD do HTML, opieka nad stroną lub blogiem
email: edyta.tarnowska@gmail.com

# Build settings

markdown: kramdown
permalink: pretty

sass:
  sass_dir: assets/css
  style: :nested

de:
  date:
    abbr_daynames: ['So', 'Mo', 'Di', 'Mi', 'Do', 'Fr', 'Sa']
    daynames: ['Sonntag', 'Montag', 'Dienstag', 'Mitwoch', 'Donnerstag', 'Freitag', 'Samstag']
    abbr_monthnames: ['Jan', 'Feb', 'Mär', 'Apr', 'Mai', 'Jun', 'Jul', 'Aug', 'Sep', 'Okt', 'Nov', 'Dez']
    monthnames: ['Januar', 'Februar', 'März', 'Apriiil', 'Mai', 'Juni', 'Juli', 'August', 'September', 'Oktober', 'November', 'Dezember']
